### ISSUE TITLE
NavCog terminated abnormally on measuring.

### ISSUE THREAD

**Issue by ferretdayo** [hulop/NavCog2#43]
Please watch video from url.
https://drive.google.com/file/d/0B6zmFeH08nWMeTRpRkNFYkkwMm8/view

I did following action.
1. selected "データ取得" button.
2. clicked "開始" button.

but, if clicked "開始" button, terminated abnormally.

**Comment by dsato80** [comment]
We will fix the termination bug but please specify a UUID, a major, and edge ID first.

**Comment by ferretdayo** [comment]
If I input a UUID, a major and edge ID, NavCog was able to measure.

I'm sorry I did not input those.

thank you.

**Comment by dsato80** [comment]
Great! Feel free to ask us if you have any question.
